"""cria tabela de respostas

Revision ID: 1969a03140ad
Revises: 9594b7660af6
Create Date: 2022-05-10 17:42:14.423595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1969a03140ad'
down_revision = '9594b7660af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
