"""cria tabelas

Revision ID: 3e522ae5b217
Revises: 919290bb4c94
Create Date: 2022-05-10 17:45:10.944016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e522ae5b217'
down_revision = '919290bb4c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('palavra_chave', sa.String(), nullable=False),
    sa.Column('texto_pergunta', sa.TEXT(), nullable=False),
    sa.Column('imagem', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pergunta_id'), 'pergunta', ['id'], unique=False)
    op.create_index(op.f('ix_pergunta_palavra_chave'), 'pergunta', ['palavra_chave'], unique=False)
    op.create_table('resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('texto_resposta', sa.TEXT(), nullable=False),
    sa.Column('imagem', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['pergunta_id'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resposta_id'), 'resposta', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resposta_id'), table_name='resposta')
    op.drop_table('resposta')
    op.drop_index(op.f('ix_pergunta_palavra_chave'), table_name='pergunta')
    op.drop_index(op.f('ix_pergunta_id'), table_name='pergunta')
    op.drop_table('pergunta')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
