"""cria tabela de perguntas

Revision ID: 919290bb4c94
Revises: 1969a03140ad
Create Date: 2022-05-10 17:42:30.726055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919290bb4c94'
down_revision = '1969a03140ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
